Add an option to remove username
openzim/sotoki pull request #189
Opened 2021-02-12 20:44 UTC by dattaz

Fix #183

2021-02-15 12:25 UTC, rgaudin requested changes
Thanks @dattaz 

In this version, the username is still visible on the user's profile page, which is still both included and linked via the avatar.
The displayName should be removed there as well.

We know that in the Bard context we'd also use `--no-userprofile` and `--nopic` but it's just not consistent.

@kelson42, do we want to to have this feature separated (as it is now) or do we want it to automatically enable --no-user-profile ?

2021-02-15 12:25 UTC, rgaudin commented on sotoki/sotoki.py
> +  --no-username                                 Doesn't include user profiles
That's not what it does

2021-06-06 10:20 UTC, kelson42 commented
@dattaz @rgaudin I’m not sure what we should do with this PR?

2021-06-06 10:55 UTC, rgaudin commented
targets previous code base. we have no choice but to close it

2021-06-06 10:55 UTC, closed without merging