Use MD5 when naming image files
openzim/sotoki pull request #289
Opened 2023-07-25 23:14 UTC by sam-masaki

This changes the way image files are named from the more collision-prone Adler32 checksums to MD5 hashes

#284

2023-07-26 08:29 UTC, rgaudin requested changes

2023-07-26 08:29 UTC, rgaudin commented on src/sotoki/utils/imager.py
> +        return hashlib.md5(url.encode("UTF-8"), usedforsecurity=False).hexdigest()
`usedforsecurity` is 3.9+ only while sotoki currently uses `3.8` in the Image and even (probably incorrectly) targets `3.6+` in the setup. Can you remove the param?

2023-07-26 16:34 UTC, rgaudin commented on src/sotoki/utils/imager.py
> +        return hashlib.md5(url.encode("UTF-8")).hexdigest()
Thank you! You need to re-request the review if you're ready.
Before you do that, can you add a `  # nosec` comment at the end of the line so Codefactor doesn't complain?

2023-07-27 17:41 UTC, rgaudin requested changes

2023-07-27 17:41 UTC, rgaudin commented on src/sotoki/utils/imager.py
> +        return hashlib.md5(url.encode("UTF-8")).hexdigest()  #nosec
:+1 ; mind adding the missing space?
```suggestion
        return hashlib.md5(url.encode("UTF-8")).hexdigest()  # nosec
```

2023-07-27 17:42 UTC, sam-masaki commented on src/sotoki/utils/imager.py
> +        return hashlib.md5(url.encode("UTF-8")).hexdigest()  #nosec
oops

2023-07-27 17:44 UTC, rgaudin approved these changes

2023-07-27 17:54 UTC, merged